spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_stater_db
    username: postgres
    password: 1234

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  jwt:
    secret: ${JWT_SECRET:PjrJwcOaMsduj7k5PO4i1On2BnaeR/8DcKla/P5cq5ewz0JVyQQgtcHkvsbc4jtPclF7kJegfpSFAJrpuV9Dcg==}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

server:
  port: 8083